import type { Metadata } from "next";
import StoreProvider from "@/app/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body style={{padding: 0, margin: 0}}>
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
